// This file is generated by Slice Machine. Update with care!

import ContentPageSlice from './ContentPageSlice';

export {
	ContentPageSlice,
};

export const components = {
	content_page_slice: ContentPageSlice,
};
