import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSinglePrismicDocument } from '@prismicio/react'

export default function Home() {

  const [ document ] = useSinglePrismicDocument("reppeatavke");
  console.log('document', document)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {document?.data?.title}
        </h1>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export async function getStaticProps() {



  return {
    props: {
      url: '/'
    },
  }
}